### ISSUE TITLE
Junit5 tests fail without vertx-rx-java libraries on classpath

### ISSUE THREAD

**Issue by fedinskiy** [vert-x3/vertx-junit5#97] opened 2021-02-08 11:24 UTC
### Version

3.9.5

### Context

I encountered an exception which looks suspicious while trying to create the basic test example.

### Do you have a reproducer?
* https://github.com/fedinskiy/reproducer/tree/bug/reactive

`mvn clean test -f pom.xml` fails
`mvn clean test -f rpom.xml` works as expected.

The only difference between two pom files is two dependecies: vertx-rx-java and vertx-rx-java2

### Steps to reproduce

1. Create project, which will use junit5 tests.
2. Run any test
3. There will be an exception `java.lang.NoClassDefFoundError: io/vertx/rxjava/core/Vertx`

It looks like classes `io.vertx.rxjava.core.Vertx` and `io.vertx.reactivex.core.Vertx` are required by VertxExtension class, however  library vertx-junit5 doesn't depend on  vertx-rx-java and vertx-rx-java2 directly. Therefore, these two libraries are required for tests, but there is no way a user can learn about it.
### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by jponge** [comment] 2021-02-16 14:56
This is a duplicate of #93 and fixed in #94

**Closed by jponge** 2021-02-16 14:56 UTC
Labels: duplicate
